---
sidebar: sidebar_aws
permalink: aws/concept_overview.html
keywords: Cloud Volumes Service for AWS, overview, concepts, features, use cases, prerequisites, workflow
summary: Cloud Volumes are simple to use and fast to deploy. Some prerequisites apply for using Cloud Volumes Service for AWS.
---

= Cloud Volumes Service for AWS overview
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes are simple to use and fast to deploy.  Some prerequisites apply for using Cloud Volumes Service for AWS.

== Benefits of using Cloud Volumes Service for AWS

Cloud Volumes Service for AWS provides the following benefits:

* Consistent high performance
* Data protection without performance impacts
* Instant cloning to support operations, development, and test workflows
* Secure access to Linux and Windows Elastic Container Service (ECS) instances
* Fully managed service, therefore no need to configure or manage storage devices
* Choice of bundled and pay-as-you-go pricing

== Prerequisites

You must have subscribed to Cloud Volumes Service for AWS before you can perform the Cloud Volumes tasks that are described in this documentation.  The subscription process includes the initial setup and configuration that are required for using the service.

See the https://www.netapp.com/us/forms/campaign/register-for-netapp-cloud-volumes-for-aws.aspx?hsCtaTracking=4f67614a-8c97-4c15-bd01-afa38bd31696%7C5e536b53-9371-4ce1-8e38-efda436e592e[Get a first look at the new NetApp Cloud Volumes Service for AWS^] page for more information.
