---
sidebar: sidebar_aws
permalink: aws/reference_known_issues.html
keywords: Cloud Volumes Service for AWS limitations and known issues
summary: The following known issues and limitations exist in Cloud Volumes Service for AWS.
---

= Known Issues and limitations
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following known issues and limitations exist in Cloud Volumes Service for AWS.

* *Issue*: In release v1.1.81 the API endpoint is no longer listed on the API access page.
+
*Workaround*: You can determine the endpoint from the URL in the browser window appended with ":8080/v1/"; meaning port *8080*, path */v1/*. For example, for the us-west-1 region, the API endpoint is https://cv.us-west-1.netapp.com:8080/v1/

* *Issue*: The service level names in the RESTful APIs do not match the names defined in the user interface. Use the correct name when defining the service level using the APIs.
+
[cols=2*,options="header",cols="50,50",width="50%"]
|===
| UI Service Level Name
| API Service Level Name
| Standard | basic
| Premium | standard
| Extreme | extreme
|===
+
See link:reference_selecting_service_level_and_quota.html[Selecting the appropriate service levels] for more information on service levels.
