---
sidebar: sidebar_aws
permalink: aws/reference_whats_new_cloud_volumes_aws.html
keywords: Cloud Volumes Service for AWS, what's new, features, enhancements
summary: NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.
---

= What's new in Cloud Volumes Service for AWS
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.

toc::[]

== August 2018


```ruby
require 'sinatra'

get '/hi' do
  "Hello World!"
end
```

1.
```
curl -s -H accept:application/json -H "Content-type: application/json" -H api-key:<api_key> -H secret-key:<secret_key> -X GET <api_url>/v1/FileSystems | jq
```
```ruby
[
  {
    [blue]#"created"#: "2018-07-05T18:58:23.000Z",
    [blue]#"fileSystemId"#: "07c9ab6c-b655-a9fe-f904-b9b97ef9baaa",
    [blue]#"lifeCycleState"#: "available",
    [blue]#"lifeCycleStateDetails"#: "Available for use",
    [blue]#"name"#: "SMB",
    [blue]#"ownerId"#: "d38839c3-a37f-4426-9ef9-ae7569e59f1d",
    [blue]#"region"#: "us-west",
    [blue]#"creationToken"#: "prickly-bellicose-archimedes",
    "quotaInBytes": 1000000000000,
    "serviceLevel": "standard",
    "snapReserve": 0,
    "timezone": "PT",
    "usedBytes": 0
  }
]
```

=======================.
2:

```ruby
curl -s -H accept:application/json -H "Content-type: application/json" -H api-key:<api_key> -H secret-key:<secret_key> -X GET <api_url>/v1/FileSystems | jq
[
  {
    [blue]#"created"#: "2018-07-05T18:58:23.000Z",
    [blue]#"fileSystemId"#: "07c9ab6c-b655-a9fe-f904-b9b97ef9baaa",
    [blue]#"lifeCycleState"#: "available",
    [blue]#"lifeCycleStateDetails"#: "Available for use",
    [blue]#"name"#: "SMB",
    [blue]#"ownerId"#: "d38839c3-a37f-4426-9ef9-ae7569e59f1d",
    [blue]#"region"#: "us-west",
    [blue]#"creationToken"#: "prickly-bellicose-archimedes",
    "quotaInBytes": 1000000000000,
    "serviceLevel": "standard",
    "snapReserve": 0,
    "timezone": "PT",
    "usedBytes": 0
  }
]
```
=====================================.
3:
``
curl -s -H accept:application/json -H "Content-type: application/json" -H api-key:<api_key> -H secret-key:<secret_key> -X GET <api_url>/v1/FileSystems | jq
[
  {
    [blue]#"created"#: [green]#"2018-07-05T18:58:23.000Z",#
    [blue]#"fileSystemId"#: [green]#"07c9ab6c-b655-a9fe-f904-b9b97ef9baaa",#
    [blue]#"lifeCycleState"#: [green]#"available"#,
    [blue]#"lifeCycleStateDetails"#: [green]#"Available for use"#,
    [blue]#"name"#: "SMB",
    [blue]#"ownerId"#: "d38839c3-a37f-4426-9ef9-ae7569e59f1d",
    [blue]#"region"#: "us-west",
    [blue]#"creationToken"#: "prickly-bellicose-archimedes",
    "quotaInBytes": 1000000000000,
    "serviceLevel": "standard",
    "snapReserve": 0,
    "timezone": "PT",
    "usedBytes": 0
  }
]
``

* Ability to select Data Encryption for SMB shares
* Ability to select the security styles of NTFS or UNIX for shares exported via both NFS and SMB
* Display for NFS and SMB mount instructions for shares exported via both NFS and SMB
* Support for multiple Active Directory servers
* RestFul API support and online examples
+
link:aws/reference_cloud_volumes_apis.html[Cloud Volume APIs]
