---
sidebar: sidebar_aws
permalink: aws/reference_whats_new_cloud_volumes_aws.html
keywords: Cloud Volumes Service for AWS, what's new, features, enhancements, limitations, known issues
summary: NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.
---

= What's new in Cloud Volumes Service for AWS
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.

== New features and updates

NetApp periodically updates the Cloud Volumes Service to bring you new features, enhancements, and bug fixes.

=== March 2019
* Added support for Microsoft Active Directory in the AWS Cloud (AWS Managed Microsoft AD) for SMB cloud volumes.

=== February 2019
* Beta release of Cloud Backup Service for US-WEST-2: link:reference_cloud_backup_service_intro.html[Managing backups using Cloud Backup Service (beta for US-WEST-2)]

=== January 2019
* NetApp Cloud Volumes Service is now publicly available on the https://aws.amazon.com/marketplace/pp/B07MF4GHYW?qid=1548352732912&sr=0-1&ref_=srh_res_product_title[AWS Marketplace^]
* Access from on-prem clients is now supported via AWS Direct Connect and Virtual Private Gateways
* A service status webpage is now available at https://status.services.cloud.netapp.com/ so you can verify availability of the CVS service in each supported region

=== December 2018
* NetApp Cloud Sync support is now available from the Cloud Volumes Service user interface in all supported regions

=== November 2018
* Support for SMB 2.1 protocol
* Support in the following AWS regions: ap-northeast-1 (Tokyo), ap-southeast-2 (Sydney), and eu-west-2 (London)

=== September 2018
* RESTful API support and online examples: link:reference_cloud_volume_apis.html[Cloud Volume APIs]
* Support in the following AWS regions: eu-central-1 (Frankfurt) and eu-west-1 (Ireland)

=== August 2018

* Ability to select data encryption for SMB shares
* Ability to select the security styles of NTFS or UNIX for shares exported via both NFS and SMB
* Display for NFS and SMB mount instructions for shares exported via both NFS and SMB
* Support for multiple Active Directory servers
* Support in the following AWS regions: us-east-1 (N. Virginia), us-west-1 (N. California), and us-west-2 (Oregon)

== Known problems and limitations

These known limitations identify platforms or features that are not fully supported.

* *Issue*: An error message "There was a problem listing volumes: Authentication failure" and "There was a problem listing mount targets: [object Object]" may be intermittently displayed.
+
*Workaround*: Retry the task or refresh the screen to correctly list the objects.

* *Issue*: 403 errors are intermittently received in response to an API call.
+
*Workaround*: Retry the API call.
